### ISSUE TITLE
Errors found when running edit-types 2.0.0 over `eswiki`

### ISSUE THREAD

**Issue by xabriel** [geohci/edit-types#74] opened 2022-11-27 04:22 UTC
I found the following four unique errors while running version 2.0.0, simple mode, over the set of all revisions of `eswiki` from 2021:

```
+-----------+------------------+-------------------+--------+------------+--------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
|revision_id|revision_parent_id|revision_timestamp |snapshot|is_user_anon|language|wiki_db|edit_type|edit_action                                                                                                                                                      |edit_count|
+-----------+------------------+-------------------+--------+------------+--------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
|71929351   |71835365          |2014-01-16 01:09:47|2022-08 |true        |es      |eswiki |error    |Unexpected err=This is a bug and should be reported. Info: Python tokenizer exited with BadRoute., type(err)=<class 'mwparserfromhell.parser.errors.ParserError'>|1         |
|100593897  |100575795         |2017-07-20 17:50:38|2022-08 |false       |es      |eswiki |error    |Unexpected err=maximum recursion depth exceeded while calling a Python object, type(err)=<class 'RecursionError'>                                                |1         |
|30809767   |30809738          |2009-10-22 14:17:08|2022-08 |true        |es      |eswiki |error    |Unexpected err=maximum recursion depth exceeded in comparison, type(err)=<class 'RecursionError'>                                                                |1         |
|341076     |269234            |2004-09-26 19:51:34|2022-08 |true        |es      |eswiki |error    |Unexpected err='Text' object has no attribute 'tag', type(err)=<class 'AttributeError'>                                                                          |1         |
+-----------+------------------+-------------------+--------+------------+--------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
```

The frequency of these errors over `eswiki` is as follows:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
|edit_action                                                                                                                                                      |count |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
|Unexpected err=maximum recursion depth exceeded while calling a Python object, type(err)=<class 'RecursionError'>                                                |1     |
|Unexpected err=This is a bug and should be reported. Info: Python tokenizer exited with BadRoute., type(err)=<class 'mwparserfromhell.parser.errors.ParserError'>|2     |
|Unexpected err=maximum recursion depth exceeded in comparison, type(err)=<class 'RecursionError'>                                                                |13    |
|Unexpected err='Text' object has no attribute 'tag', type(err)=<class 'AttributeError'>                                                                          |668702|
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
```

**Comment by geohci** [comment] 2022-12-02 21:04
hmm...thanks for the bug report. I'll look into this. My guess is the recursion depth might be malformed wikitext that is making mwparserfromhell blow up but that could probably be caught still and some sort of contingency plan put into place. The tokenizer one clearly is also mwparserfromhell so same thing applies.

I'll have to look into the Tag error which clearly is a much bigger issue -- I thought I had fixed most of that but must have missed something. Do you happen to have an example revision ID handy so I can manually inspect (if not, no worries, I'll dig around)?

**Comment by geohci** [comment] 2022-12-02 21:09
Oh no wait, it's a half-patched thing on my local computer that I haven't committed yet because there were some remaining details (:face-palm:). The cause seemed to be that the parsing of text formatting (a type of Tag) is very context dependent so when I parse the full document, a node might be labeled as a Bold formatting tag but then when I later reparse it in isolation, it's instead interpreted as Text. I'll work to get a patch and v2.0.1 out in the next week.

**Comment by xabriel** [comment] 2022-12-02 22:55
> I'll have to look into the Tag error which clearly is a much bigger issue -- I thought I had fixed most of that but must have missed something. Do you happen to have an example revision ID handy so I can manually inspect

Yes the unique error samples above include `revision_id`.

> I'll work to get a patch and v2.0.1 out in the next week.

No rush! And thanks for looking into this!

**Comment by geohci** [comment] 2022-12-05 22:44
FYI #77 in case you're curious -- has the Text Formatting and tag fixes. I haven't looked into the recursion depth stuff yet. I'll probably merge in the next day or so unless you'd like more time to actually review (no problem with me).

**Comment by xabriel** [comment] 2022-12-06 15:28
> unless you'd like more time to actually review (no problem with me)

It will take me a bit to rerun against `eswiki`, so don't want to block you. So please go ahead with changes. Whenever I rerun, I will report back my findings here.

**Comment by geohci** [comment] 2022-12-06 18:55
Great -- new releases are easy too so if it's not doing what we expect, we can just patch again.

**Comment by xabriel** [comment] 2022-12-16 17:57
After re-running the same workload with `2.0.1`, the count of errors is drastically down because one error class is gone:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|edit_action                                                                                                                                                      |count|
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|Unexpected err=maximum recursion depth exceeded while calling a Python object, type(err)=<class 'RecursionError'>                                                |13   |
|Unexpected err=This is a bug and should be reported. Info: Python tokenizer exited with BadRoute., type(err)=<class 'mwparserfromhell.parser.errors.ParserError'>|2    |
|Unexpected err=maximum recursion depth exceeded in comparison, type(err)=<class 'RecursionError'>                                                                |1    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
```

**Comment by geohci** [comment] 2022-12-20 16:07
Excellent -- the other three seem to be `mwparserfromhell` errors so I'm not sure we can overcome them without fixing `mwparserfromhell` directly. do you think they should be caught more explicitly by the edit types library?

**Comment by xabriel** [comment] 2022-12-20 16:38
> do you think they should be caught more explicitly by the edit types library?

I think the context given by the stack trace is good enough. Once I have some time I will investigate the second one that starts with `This is a bug and should be reported....` and will open a bug for `mwparserfromhell`.

And you know, we now have 16 errors out of millions and millions of successful diffs, so I think we can close this one.

Thanks for all the fixes @geohci !

**Comment by geohci** [comment] 2022-12-22 16:40
> And you know, we now have 16 errors out of millions and millions of successful diffs, so I think we can close this one.
> Once I have some time I will investigate the second one that starts with This is a bug and should be reported.... and will open a bug for mwparserfromhell.

Many thanks! Related: FYI I knocked stat1008 briefly out of commission the other week because I had a job that was just sequentially parsing the edit history via the XML dumps from a smaller Wikipedia language edition (Vietnamese I believe) to generate some stats and the memory usage rose to many GBs. Memory usage should have stayed pretty low because the processing was sequential and the memory should have essentially cleared with each new diff so definitely suggests that there's some sort of memory leak I assume with mwparserfromhell. I haven't tried with the C parser turned off to see if that makes a difference but that would be an obvious next step to help isolate the issue.

**Closed by geohci** 2022-12-22 16:40 UTC

**Comment by xabriel** [comment] 2022-12-22 18:27
> so definitely suggests that there's some sort of memory leak I assume with mwparserfromhell

Interesting!

> I haven't tried with the C parser turned off to see if that makes a difference but that would be an obvious next step to help isolate the issue.

Do please let me know if you do try and the outcome of it. Thanks!
